### ISSUE TITLE
Apply - Error: invalid patch file - no data

### ISSUE THREAD

**Issue by cooktheryan** [konveyor/crane-lib#23]
When a patch file does not exist when trying to transform the process will fail

**Comment by sseago** [comment]
I would think that the proper behavior for a missing patch file would the same as for a zero-length patch file.

**Comment by cooktheryan** [comment]
@sseago I needed to follow up with this bug but zero-length and missing fail. 

Empty
```
rcook (minikube)  @ /tmp/crane
transform-cmd└─ $ cat transform/resources/default/transform-ConfigMap_default_kube-root-ca.crt.yaml 
rcook (minikube)  @ /tmp/crane

./crane apply --export-dir /tmp/export --transform-dir /tmp/transform --output-dir /tmp/outputs
Error: invalid patch file - no data


```

Missing
```
./crane apply --export-dir /tmp/export --transform-dir /tmp/transform --output-dir /tmp/outputs
Error: open /tmp/transform/resources/default/transform-ConfigMap_default_kube-root-ca.crt.yaml: no such file or directory
Usage:
  crane apply [flags]

Flags:
  -e, --export-dir string      The path where the kubernetes resources are saved (default "export")
  -h, --help                   help for apply
  -o, --output-dir string      The path where files are to be saved after transformation are applied (default "output")
  -t, --transform-dir string   The path where files that contain the transformations are saved (default "transform")
```

**Comment by sseago** [comment]
Ahh. If zero-length fails, that does sound like a bug, since that's exactly what we get out of the transform lib in cases where the plugin doesn't provide any changes. I haven't actually used the apply feature myself yet, so I hadn't tested that part directly yet. It's also possible that the correct thing for transform to do if there's no patch content is to *not* create the file at all (and delete it if it exists). Either way, the apply lib needs to be able to handle "don't do anything to this resource".

**Comment by cooktheryan** [comment]
@sseago but I wonder if there is not transform to apply to a resource if we just pass it as is it the outputs directory? That would save us from scenario's that we may not properly have rules established for but a customer may be using. I'm thinking any special CRD could be a nightmare for us.

**Comment by sseago** [comment]
@cooktheryan So the plugins don't actually modify the resources -- they return a patch to modify the resource and a whiteout bool to tell whether the resource should be removed from the output. What you're describing would be a plugin that basically always set whiteout to false and returned an empty patch. We could create such a plugin, although it would be identical in effect to running transform with no plugins. Running the "do nothing" plugin in addition to another plugin would be equivalent to running just the other plugin. It might be useful for testing purposes, bit it would be a waste of processing time for actual transforms.

**Comment by cooktheryan** [comment]
I think I was just looking at it from the point of view that whatever comes out of the apply would be like a golden ticket of a namespace or cluster. Right now things break at the apply level because empty files are created during transform even if the plugin does not modify them so when you go to run transform apply you are hit with `invalid patch file - no data`. I think we definitely have to fix that.

I wonder if the fix for this in my situation is to just do a copy export outputs to a location and then copy over top of them the apply outputs leaving us our "golden image".

**Comment by sseago** [comment]
@cooktheryan That's been fixed in crane-lib, and https://github.com/konveyor/crane/pull/11 updates to use the new crane-lib code. Now the patch file that's created when there is no plugin applied is simply "[]" -- while I haven't tested this yet with a plugin that returns empty patches, it *should* do the same thing.

**Comment by cooktheryan** [comment]
fantastic! Once merged ill give it a whirl and close this if everything looks clean. Have a good night @sseago Thanks!!

**Comment by shawn-hurley** [comment]
Going to assume this is working and close, as no comment has been made. Please re-open if you are still seeing this issue.
