### ISSUE TITLE
Add BuildConfig to Openshift binary plugin

### ISSUE THREAD

**Issue by sseago** [konveyor/crane-lib#61]
For BuildConfigs, we need to deal with pull secrets. For velero plugins, we swap out secrets on restore based listing actual in-cluster secrets. Here we need to accept a mapping of secrets to swap. For now, any secrets found in the BuildConfig that don't match the input map won't be modified.

In addition, once we have this logic in place for BuildConfigs, we should do the same for pod pull secrets.

The final thing needed here is to set the whiteout flag for Build resources.

**Comment by shawn-hurley** [comment]
Closing as fixed by PR.
