### ISSUE TITLE
openshift example plugin returns error code 2

### ISSUE THREAD

**Issue by eriknelson** [konveyor/crane-lib#65]
Hey folks, sorry for the messy output but I'm seeing this error when trying to use the openshift example plugin:

```
ERRO[0000] unable to run the plugin binary               pluginPath=/git/hello-crane-demo/bin/plugins/open
shift                                                                                                     ERRO[0000] error running the plugin command              pluginPath=/git/hello-crane-demo/bin/plugins/open
shift                                                                                                     
Error: error running the plugin command: unable to run the plugin binary, err: exit status 2 
```

Spent some time trying to understand where this is happening with @pranavgaikwad but it wasn't clear to us what was going on. I swapped it out for the service plugin, and that seemed to work fine, so that suggests there's something in the example plugin that's not happy with the current plugin interface.

Separate question for discussion: how do we expect people to debug these plugins best? Should we think about what we want that experience to be like, like an optional flag that dumps some diagnostic info?

**Comment by eriknelson** [comment]
@pranavgaikwad spotted:

https://github.com/konveyor/crane-lib/blob/e077c6bf9b666c3aaa85946e8e924ebf0c632dc7/transform/binary-plugin/examples/openshift/cmd.go#L38
4:33
https://github.com/konveyor/crane-lib/blob/e077c6bf9b666c3aaa85946e8e924ebf0c632dc7/transform/binary-plugin/examples/openshift/cmd.go#L16
4:33
notice V1 vs v1

PR incoming. I'll file a separate issue to implement some good validation here to protect plugin authors.

**Comment by sseago** [comment]
This plugin hasn't been tested/used since the recent refactoring. It's on my list to revise it, add some functionality, and start testing it later today or Monday.

**Comment by sseago** [comment]
Actually, from what I'm seeing, the error is not caused by the "V1" vs. "v1" string difference but because the `logger.Info()` calls are breaking the expected stdout data format.

**Comment by eriknelson** [comment]
+1 think I realized this afterwards

**Comment by sseago** [comment]
Initializing the logger properly in the plugin removes the error code output. PR forthcoming, including other openshift plugin fixes.

**Comment by shawn-hurley** [comment]
@sseago @eriknelson I believe that this should be fixed by the latest release. Can we close this issue?

**Comment by sseago** [comment]
@shawn-hurley This should be fixed now. If @eriknelson concurs, lets close it.

**Comment by eriknelson** [comment]
+1
