### ISSUE TITLE
Service example plugin strips clusterIP, I'm still seeing clusterIPs

### ISSUE THREAD

**Issue by eriknelson** [konveyor/crane-lib#66]
```
spec:
  clusterIPs:
  - 172.30.108.211
```

Think we still probably want to strip this?

**Comment by eriknelson** [comment]
Here's my lazy patch to resolve: https://gist.github.com/eriknelson/9372f300b6e3952c3141a78dea5ee032

**Comment by sseago** [comment]
Oh, fun. This is a field that's new in kube 1.20. Something like the above logic is what we need, with an added existence check -- if the field doesn't exist, we don't remove it.

**Comment by sseago** [comment]
Resolved by https://github.com/konveyor/crane-lib/pull/67

**Comment by shawn-hurley** [comment]
@sseago I think that we can close this issue as
1. This particular example was removed
2. We have updated the internal k8s plugin to do the correct thing right

if these are correct I think it makes sense to close this issue.
